### ISSUE TITLE
The output of the computing nodes is called 'bits' but this is no longer general enough

### ISSUE THREAD

**Issue by stephendiadamo** [Interlin-q/Interlin-q#43]
https://github.com/Interlin-q/Interlin-q/blob/65e2841396f82fb3b2166736abd376cd79ffa8cd/interlinq/components/computing_host.py#L585

An incoming feature is to allow computing hosts to compute expectation value directly and send back the expectation value. The value sent back is contained in the 'bits' field but this is misleading when the value is a decimal value. 

Let's change 'bits' to 'val' or 'output' to accommodate this.

**Comment by Shiro-Raven** [comment]
Fixed it, will link to the coming pull request
